<a href="https://colab.research.google.com/github/Aifa-Chris/Cousera_Capstone/blob/master/Cousera_Capstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

I am moving to Toronto, but I’ve never been there before. A friend mentioned that I may like to like in the Downtown Toronto Borough, but did not tell me which neighborhood to live in. First, I want to see on a map where the neighborhoods in Downtown Toronto are on a map. Then I would like to see the top venues in each neighborhood to help me determine which neighborhood to live in. I would like to be near bars, restaurants, coffee shops and museums. 

The data I will be using is; 

•	Toronto Borough and Neighborhood from Wikipedia, read into dataframe Toronto
•	Geospatial Coordinates from CSV added to dataframe Toronto
•	New dataframe with just the Downtown Toronto Neighborhoods. 
•	Venue data pulled from Foursquare for Downtown Toronto Neighborhoods

This data will be used to:

•	Identify Downtown Toronto Neighborhoods on a map
•	Identify top venues in each Downtown Toronto Neighborhood
•	Isolate which neighborhood has desired venues

In [1]:
import pandas as pd
import numpy as np
import requests

! pip install geocoder
import geocoder

Collecting geocoder
  Downloading https://files.pythonhosted.org/packages/4f/6b/13166c909ad2f2d76b929a4227c952630ebaf0d729f6317eb09cbceccbab/geocoder-1.38.1-py2.py3-none-any.whl (98kB)
     |████████████████████████████████| 102kB 3.1MB/s
Requirement already satisfied: click in /usr/local/lib/python3.6/dist-packages (from geocoder) (7.1.1)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from geocoder) (2.21.0)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from geocoder) (0.16.0)
Collecting ratelim
  Downloading https://files.pythonhosted.org/packages/f2/98/7e6d147fd16a10a5f821db6e25f192265d6ecca3d82957a4fdd592cad49c/ratelim-0.1.6-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from geocoder) (1.12.0)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->geocoder) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->geocoder) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->geocoder) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->geocoder) (1.24.3)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/dist-packages (from ratelim->geocoder) (4.4.2)
Installing collected packages: ratelim, geocoder
Successfully installed geocoder-1.38.1 ratelim-0.1.6

In [2]:
data = "https://en.wikipedia.org/w/index.php?title=List_of_postal_codes_of_Canada:_M&oldid=890001695"
Toronto = pd.read_html(data)[0]
Toronto.head(10)
# Make the dataframe (Using old html link)

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M5A  Downtown Toronto       Regent Park
6      M6A        North York  Lawrence Heights
7      M6A        North York    Lawrence Manor
8      M7A      Queen's Park      Not assigned
9      M8A      Not assigned      Not assigned

In [3]:
Toronto1 = Toronto.replace('Not assigned', np.nan)
Toronto2 = Toronto1.dropna()
Toronto2
#Prepping data for dropna(), droping NaN

    Postcode           Borough             Neighbourhood
2        M3A        North York                 Parkwoods
3        M4A        North York          Victoria Village
4        M5A  Downtown Toronto              Harbourfront
5        M5A  Downtown Toronto               Regent Park
6        M6A        North York          Lawrence Heights
..       ...               ...                       ...
282      M8Z         Etobicoke  Kingsway Park South West
283      M8Z         Etobicoke                 Mimico NW
284      M8Z         Etobicoke        The Queensway West
285      M8Z         Etobicoke     Royal York South West
286      M8Z         Etobicoke            South of Bloor

[210 rows x 3 columns]

In [4]:
Toronto3= Toronto2.groupby([ 'Postcode']).agg(lambda x:" , ".join(x))
Toronto3
#Grouping by Postcode, Borough

                                                    Borough                                      Neighbourhood
Postcode
M1B                               Scarborough , Scarborough                                    Rouge , Malvern
M1C                 Scarborough , Scarborough , Scarborough           Highland Creek , Rouge Hill , Port Union
M1E                 Scarborough , Scarborough , Scarborough                Guildwood , Morningside , West Hill
M1G                                             Scarborough                                             Woburn
M1H                                             Scarborough                                          Cedarbrae
...                                                     ...                                                ...
M9N                                                    York                                             Weston
M9P                                               Etobicoke                                          Westmount
M9R           Etobicoke , Etobicoke , Etobicoke , Etobicoke  Kingsview Village , Martin Grove Gardens , Ric...
M9V       Etobicoke , Etobicoke , Etobicoke , Etobicoke ...  Albion Gardens , Beaumond Heights , Humbergate...
M9W                                               Etobicoke                                          Northwest

[102 rows x 2 columns]

In [5]:
Toronto3.shape

(102, 2)

In [7]:
#Load coordinates, rename column to match
Coordinates = pd.read_csv('Geospatial_Coordinates.csv')
Coordinates1= Coordinates.rename(columns={'Postal Code':'Postcode'})
Coordinates1.head()

  Postcode   Latitude  Longitude
0      M1B  43.806686 -79.194353
1      M1C  43.784535 -79.160497
2      M1E  43.763573 -79.188711
3      M1G  43.770992 -79.216917
4      M1H  43.773136 -79.239476

In [8]:
# Merge coordinates with Grouped Dataframe
Toronto4 = Toronto3.merge(Coordinates1, on='Postcode', how="left")
Toronto4

    Postcode  ...  Longitude
0        M1B  ... -79.194353
1        M1C  ... -79.160497
2        M1E  ... -79.188711
3        M1G  ... -79.216917
4        M1H  ... -79.239476
..       ...  ...        ...
97       M9N  ... -79.518188
98       M9P  ... -79.532242
99       M9R  ... -79.554724
100      M9V  ... -79.588437
101      M9W  ... -79.594054

[102 rows x 5 columns]

In [35]:
# Identifying which neighborhoods are in Downtown Toronto
Search = Toronto4.loc[Toronto4.Borough == 'Downtown Toronto']
Search

   Postcode           Borough  ...   Latitude  Longitude
50      M4W  Downtown Toronto  ...  43.679563 -79.377529
52      M4Y  Downtown Toronto  ...  43.665860 -79.383160
55      M5C  Downtown Toronto  ...  43.651494 -79.375418
56      M5E  Downtown Toronto  ...  43.644771 -79.373306
57      M5G  Downtown Toronto  ...  43.657952 -79.387383
69      M5W  Downtown Toronto  ...  43.646435 -79.374846
75      M6G  Downtown Toronto  ...  43.669542 -79.422564

[7 rows x 5 columns]

In [0]:
import folium

In [39]:
#Just looking at Canada on a map
Canada_map=folium.Map(location=[43.806686,-79.194353], zoom_start=8)
Canada_map

In [12]:
#Setting up Foursquare URl
CLIENT_ID = '1SHMANHM4J44TRJGHF1PXMBNUG0BDB5J2LJ3RN0VRYQPZZVP' 
CLIENT_SECRET = 'ORLLNBGEVE1I24KFEHUNFZUHE1MX54T1DRE5C2RYJIL3ANQI' 
VERSION = '20180605' 
radius = 1000
LIMIT = 100

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: 1SHMANHM4J44TRJGHF1PXMBNUG0BDB5J2LJ3RN0VRYQPZZVP
CLIENT_SECRET:ORLLNBGEVE1I24KFEHUNFZUHE1MX54T1DRE5C2RYJIL3ANQI

In [0]:
from pandas.io.json import json_normalize

In [0]:
#Assigning categories to venues
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

In [0]:
#function to pull venues in neighborhoods
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [17]:
#Dataframe with Downtown Toronto Boroughs
Toronto5 = Toronto4[Toronto4['Borough'] == 'Downtown Toronto'].reset_index(drop=True)
Toronto5

  Postcode           Borough  ...   Latitude  Longitude
0      M4W  Downtown Toronto  ...  43.679563 -79.377529
1      M4Y  Downtown Toronto  ...  43.665860 -79.383160
2      M5C  Downtown Toronto  ...  43.651494 -79.375418
3      M5E  Downtown Toronto  ...  43.644771 -79.373306
4      M5G  Downtown Toronto  ...  43.657952 -79.387383
5      M5W  Downtown Toronto  ...  43.646435 -79.374846
6      M6G  Downtown Toronto  ...  43.669542 -79.422564

[7 rows x 5 columns]

In [18]:
#Locating Downtown Toronto Neighborhoods on map
map_Toronto = folium.Map(location=[43.806686,-79.194353], zoom_start=10.5)

for lat, lng, Neighbourhood in zip(Toronto5['Latitude'], Toronto5['Longitude'], Toronto5['Neighbourhood']):
    label = '{}'.format(Neighbourhood)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=20,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_Toronto)  
    
map_Toronto

In [24]:
# getting venues in neighborhoods, assigned to toronto_venues

toronto_venues = getNearbyVenues(names=Toronto5['Neighbourhood'],
                                   latitudes=Toronto5['Latitude'],
                                   longitudes=Toronto5['Longitude']
                                  )

Rosedale
Church and Wellesley
St. James Town
Berczy Park
Central Bay Street
Stn A PO Boxes 25 The Esplanade
Christie

In [25]:
print('There are {} uniques categories.'.format(len(toronto_venues['Venue Category'].unique())))

There are 131 uniques categories.

In [26]:
@#grouping venues
toronto_venues.groupby('Neighborhood').count()

                                 Neighborhood Latitude  ...  Venue Category
Neighborhood                                            ...
Berczy Park                                         56  ...              56
Central Bay Street                                  77  ...              77
Christie                                            18  ...              18
Church and Wellesley                                81  ...              81
Rosedale                                             4  ...               4
St. James Town                                     100  ...             100
Stn A PO Boxes 25 The Esplanade                     96  ...              96

[7 rows x 6 columns]

In [0]:
#Organizing/Normalizing by venue type
toronto_onehot = pd.get_dummies(toronto_venues[["Venue Category"]], prefix="",prefix_sep="")

toronto_onehot['Neighborhood']=toronto_venues['Neighborhood']

fixed_columns = [toronto_onehot.columns[-1]] + list(toronto_onehot.columns[:-1])
toronto_onehot = toronto_onehot[fixed_columns]

In [30]:
#Scoring by venues
toronto_grouped = toronto_onehot.groupby('Neighborhood').mean().reset_index()
toronto_grouped

                      Neighborhood  Afghan Restaurant  ...  Wings Joint  Yoga Studio
0                      Berczy Park           0.000000  ...     0.000000     0.000000
1               Central Bay Street           0.000000  ...     0.000000     0.012987
2                         Christie           0.000000  ...     0.000000     0.000000
3             Church and Wellesley           0.012346  ...     0.012346     0.024691
4                         Rosedale           0.000000  ...     0.000000     0.000000
5                   St. James Town           0.000000  ...     0.000000     0.000000
6  Stn A PO Boxes 25 The Esplanade           0.000000  ...     0.000000     0.000000

[7 rows x 132 columns]

In [0]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [38]:
num_top_venues = 20

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = toronto_grouped['Neighborhood']

for ind in np.arange(toronto_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(toronto_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted

                      Neighborhood  ... 20th Most Common Venue
0                      Berczy Park  ...              Irish Pub
1               Central Bay Street  ...             Comic Shop
2                         Christie  ...       Department Store
3             Church and Wellesley  ...         Ice Cream Shop
4                         Rosedale  ...   Ethiopian Restaurant
5                   St. James Town  ...              BBQ Joint
6  Stn A PO Boxes 25 The Esplanade  ...            Fish Market

[7 rows x 21 columns]

Based on the Venues above, I would like to live in Berczy park! It has the mix of restaurants, bars, farmers market and museums I would like to live near.